Adex dataset
Merck/metalite.ae pull request #149
Opened 2023-06-09 18:11 UTC by jeetendersinghc

2023-06-11 23:01 UTC, elong0527 commented
Let's enhance the readability of this example.

2023-06-14 01:24 UTC, nanxstats requested changes
General:

- Consider writing an [informative title and description](https://code-review.tidyverse.org/author/submitting.html) for the pull request (also the commit messages).

File structure:

- As this is the first time `data-raw/` is added, add it to `.Rbuildignore`.
- To follow the convention, use an `.R` file instead of using an `.Rmd` file.

Content:

- Minimize the namespaces used and only load the essential ones. For example, why is glue needed? Please avoid `library(tidyverse)` because it will unnecessarily inflate the number of dependencies required to run this script.
- Follow a consistent style in writing file and directory paths. For example, the leading `./` and `../` are redundant if the project is already opened.
- For code comments, please follow the style defined in the [tidyverse style guide](https://style.tidyverse.org/functions.html#comments-1) and make sure the capitalization of words are correct.
- Run `styler::style_file()` to apply the tidyverse code style.
- Run lintr on the code. Things like `# getwd()` will be marked as "commented out code should be removed".
- All exported datasets should be [documented](https://r-pkgs.org/data.html#sec-documenting-data).

2023-06-14 01:38 UTC, wangben718 commented on data-raw/adex.Rmd
> +adex1 <-ex1 %>% mutate(ASTDT = as.Date(EXSTDTC, format='%Y-%m-%d')) %>% mutate(AENDT = as.Date(EXENDTC, format='%Y-%m-%d'))
run `lintr` to style the code.

2023-07-08 17:08 UTC, elong0527 commented
The PR has opened > 30 days, tentatively close it. Please create a new PR once comments are addressed.

2023-07-08 17:08 UTC, closed without merging