142 add exposure adjusted adverse event summary table
Merck/metalite.ae pull request #155
Opened 2023-06-23 19:01 UTC by wangben718

2023-06-27 20:25 UTC, nanxstats requested changes
Do you plan to fix the error, warning, and note from the checks?

The code look good but you should use snake case for variables consistently, such as `TrtGrps`.

2023-06-28 20:47 UTC, wangben718 commented
rtf output is also updated related to #154

2023-06-29 13:36 UTC, LittleBeannie approved these changes

2023-06-30 00:39 UTC, nanxstats approved these changes
Overall looking good! I fixed a few minor style issues.

Life hack: one thing I noticed is that you have used extra curly brakets `{ }` to create code sections in functions. This is a bit unusual and creates unnecessary indentation. I removed them and instead used four trailing dashes `-` after the leading comment to create code sections. This convention is described in [code sections in RStudio IDE](https://support.posit.co/hc/en-us/articles/200484568-Code-Folding-and-Sections-in-the-RStudio-IDE):

> ... any comment line which includes at least four trailing dashes (`-`), equal signs (`=`), or pound signs (`#`) automatically creates a code section.

2023-06-30 00:39 UTC, merged