Parepare cran release
Merck/metalite.ae pull request #186
Opened 2024-03-28 17:55 UTC by wangben718

2024-03-28 19:38 UTC, LittleBeannie approved these changes

2024-04-03 00:05 UTC, nanxstats requested changes

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- `tlf_ae_summary()` and `tlf_ae_specific` now have a new argument `title` for a user-customized title.
`tlf_ae_specific()` should also have `()` for consistency

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Add `data/metalite_ae_adex.Rda`.
For `.rda`, the convention is to use all lower case `.rda`. If you data file name actually ends with `.Rda`, you need to rename it.

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Add new vignettes: 'Subgroup Analysis for Specific AE' and 'Exposure Adjusted Event Rate'.
It doesn't help to say the titles here. `vignette("vignette-file-name")` will get linked and clickable.

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Add test cases for new functions.
This belongs to "don't comment on the obvious" and thus should be removed.

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Add system organ class(SOC) information to `outdata` in `prepare_ae_specific()`
Should be styled as "System Organ Classes (SOC)" (title case and a whitespace)

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +## Bug fixes
Need a blank line between headings and content.

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Fix bug to avoid warning messages when no comparison variables are requested in `format_ae_specific()`.
Please link the PR at the end of the sentences following https://style.tidyverse.org/news.html.

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Update Github Actions workflow.
Github -> GitHub

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Add an installation section to `README.Rd`.
`README.md`

2024-04-03 00:05 UTC, nanxstats commented on NEWS.md
> +- Improve style and formatting for vignettes and codes.
codes -> code

2024-04-03 02:51 UTC, wangben718 commented
Hi @fukuhiro2023 , could you please address these issues?

2024-04-08 00:41 UTC, fukuhiro2023 commented
Hi @wangben718 and @nanxstats , I have updated the `NEWS.md` based on the comments. Please kindly review it.

2024-04-08 01:05 UTC, nanxstats approved these changes
Great, thanks for the update!

2024-04-08 01:05 UTC, merged