test 01 : prepare ae_specific
Merck/metalite.ae pull request #68
Opened 2022-07-12 16:49 UTC by srnep

2022-07-12 16:59 UTC, LittleBeannie requested changes

2022-07-12 16:59 UTC, LittleBeannie commented on tests/testthat/test-independent-testing-prepare_ae_specificr.R
> +devtools::load_all()
Hi @srnep , please remove `devtools::load_all()`.

2022-07-12 19:21 UTC, wangben718 commented on tests/testthat/test-independent-testing-prepare_ae_specificr.R
> +library(metalite.ae)
Hi @srnep . We don't have to load the package itself when validation.

2022-07-12 21:27 UTC, LittleBeannie commented on tests/testthat/test-independent-testing-prepare_ae_specificr.R
> +  expect_equal(yy %>% filter(f == 1) %>% select(-c("x_any$name", f)), tibble(pop_cnt) %>% select(-c(ITTFL)))
Hi @srnep , I only have a minor comment as I have in [Madhu's PR](https://github.com/Merck/metalite.ae/pull/69#discussion_r919421593). Could you please confirm if the derivation of `pop_cnt` is the same as that in SAS macro?

2022-07-13 14:40 UTC, LittleBeannie approved these changes

2022-07-13 14:40 UTC, merged